
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool A', 'Pool A-FRA-NZL', '2023/09/08 19:15:00', 'France', 'FRA', 'New Zealand', 'NZL');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool A', 'Pool A-ITA-NAM', '2023/09/09 11:00:00', 'Italy', 'ITA', 'Namibia', 'NAM');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool B', 'Pool B-IRL-ROM', '2023/09/09 13:30:00', 'Ireland', 'IRL', 'Romania', 'ROM');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool C', 'Pool C-AUS-GEO', '2023/09/09 16:00:00', 'Australia', 'AUS', 'Georgia', 'GEO');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool D', 'Pool D-ENG-ARG', '2023/09/09 19:00:00', 'England', 'ENG', 'Argentina', 'ARG');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool D', 'Pool D-JAP-CL', '2023/09/10 11:00:00', 'Japan', 'JAP', 'Chile', 'CL');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool B', 'Pool B-ZAF-SCO', '2023/09/10 15:45:00', 'South Africa', 'ZAF', 'Scotland', 'SCO');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool C', 'Pool C-WAL-FID', '2023/09/10 19:00:00', 'Wales', 'WAL', 'Fiji', 'FID');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool A', 'Pool A-FRA-URU', '2023/09/14 19:00:00', 'France', 'FRA', 'Uruguay', 'URU');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool A', 'Pool A-NZL-NAM', '2023/09/15 19:00:00', 'New Zealand', 'NZL', 'Namibia', 'NAM');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool D', 'Pool D-SAM-CL', '2023/09/16 13:00:00', 'Samoa', 'SAM', 'Chile', 'CL');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool C', 'Pool C-WAL-POR', '2023/09/16 15:45:00', 'Wales', 'WAL', 'Portugal', 'POR');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool B', 'Pool B-IRL-TON', '2023/09/16 19:00:00', 'Ireland', 'IRL', 'Tonga', 'TON');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool B', 'Pool B-ZAF-ROM', '2023/09/17 13:00:00', 'South Africa', 'ZAF', 'Romania', 'ROM');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool C', 'Pool C-AUS-FID', '2023/09/17 15:45:00', 'Australia', 'AUS', 'Fiji', 'FID');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool D', 'Pool D-ENG-JAP', '2023/09/17 19:00:00', 'England', 'ENG', 'Japan', 'JAP');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool A', 'Pool A-ITA-URU', '2023/09/20 15:45:00', 'Italy', 'ITA', 'Uruguay', 'URU');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool A', 'Pool A-FRA-NAM', '2023/09/21 19:00:00', 'France', 'FRA', 'Namibia', 'NAM');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool D', 'Pool D-ARG-SAM', '2023/09/22 15:45:00', 'Argentina', 'ARG', 'Samoa', 'SAM');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool C', 'Pool C-GEO-POR', '2023/09/23 12:00:00', 'Georgia', 'GEO', 'Portugal', 'POR');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool D', 'Pool D-ENG-CL', '2023/09/23 15:45:00', 'England', 'ENG', 'Chile', 'CL');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool B', 'Pool B-ZAF-IRL', '2023/09/23 19:00:00', 'South Africa', 'ZAF', 'Ireland', 'IRL');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool B', 'Pool B-SCO-TON', '2023/09/24 15:45:00', 'Scotland', 'SCO', 'Tonga', 'TON');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool C', 'Pool C-WAL-AUS', '2023/09/24 19:00:00', 'Wales', 'WAL', 'Australia', 'AUS');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool A', 'Pool A-URU-NAM', '2023/09/27 15:45:00', 'Uruguay', 'URU', 'Namibia', 'NAM');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool D', 'Pool D-JAP-SAM', '2023/09/28 19:00:00', 'Japan', 'JAP', 'Samoa', 'SAM');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool A', 'Pool A-NZL-ITA', '2023/09/29 19:00:00', 'New Zealand', 'NZL', 'Italy', 'ITA');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool D', 'Pool D-ARG-CL', '2023/09/30 13:00:00', 'Argentina', 'ARG', 'Chile', 'CL');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool C', 'Pool C-FID-GEO', '2023/09/30 15:45:00', 'Fiji', 'FID', 'Georgia', 'GEO');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool B', 'Pool B-SCO-ROM', '2023/09/30 19:00:00', 'Scotland', 'SCO', 'Romania', 'ROM');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool C', 'Pool C-AUS-POR', '2023/10/01 15:45:00', 'Australia', 'AUS', 'Portugal', 'POR');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool B', 'Pool B-ZAF-TON', '2023/10/01 19:00:00', 'South Africa', 'ZAF', 'Tonga', 'TON');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool A', 'Pool A-NZL-URU', '2023/10/05 19:00:00', 'New Zealand', 'NZL', 'Uruguay', 'URU');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool A', 'Pool A-FRA-ITA', '2023/10/06 19:00:00', 'France', 'FRA', 'Italy', 'ITA');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool C', 'Pool C-WAL-GEO', '2023/10/07 13:00:00', 'Wales', 'WAL', 'Georgia', 'GEO');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool D', 'Pool D-ENG-SAM', '2023/10/07 15:45:00', 'England', 'ENG', 'Samoa', 'SAM');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool B', 'Pool B-IRL-SCO', '2023/10/07 19:00:00', 'Ireland', 'IRL', 'Scotland', 'SCO');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool D', 'Pool D-JAP-ARG', '2023/10/08 11:00:00', 'Japan', 'JAP', 'Argentina', 'ARG');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool B', 'Pool B-TON-ROM', '2023/10/08 15:45:00', 'Tonga', 'TON', 'Romania', 'ROM');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Pool C', 'Pool C-FID-POR', '2023/10/08 19:00:00', 'Fiji', 'FID', 'Portugal', 'POR');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Q1', 'Q1-Winner Pool C-Runner-up Pool D', '2023/10/14 15:00:00', 'W_PC', 'Winner Pool C', 'R_PD', 'Runner-up Pool D');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Q2', 'Q2-Winner Pool B-Runner-up Pool A', '2023/10/14 19:00:00', 'W_PB', 'Winner Pool B', 'R_PA', 'Runner-up Pool A');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Q3', 'Q3-Winner Pool D-Runner-up Pool C', '2023/10/15 15:00:00', 'W_PD', 'Winner Pool D', 'R_PC', 'Runner-up Pool C');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('Q4', 'Q4-Winner Pool A-Runner-up Pool B', '2023/10/15 19:00:00', 'W_PA', 'Winner Pool A', 'R_PB', 'Runner-up Pool B');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('S1', 'S1-W_Q1-W_Q2', '2023/10/20 19:00:00', 'W_Q1', 'W_Q1', 'W_Q2', 'W_Q2');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('S2', 'S2-W_Q3-W_Q4', '2023/10/21 19:00:00', 'W_Q3', 'W_Q3', 'W_Q4', 'W_Q4');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('F1', 'F1-L_S1-L_S2', '2023/10/27 19:00:00', 'L_S1', 'L_S1', 'L_S2', 'L_S2');
insert into GAME (category, key, date, libteamA, teamA, libteamB, teamB) values('F2', 'F2-W_L1-W_L1', '2023/10/28 19:00:00', 'W_L1', 'W_L1', 'W_L1', 'W_L1');

